<?php

namespace minions\response;

class Code {

    const SUCCESS = 0;
    const FAIL_INTERNAL_NO_RESPONSE = 4000;
    const FAIL_INTERNAL_NO_CODE   = 4001;
    const FAIL_INTERNAL_EXCEPTION  = 4002;
    const FAIL_INTERNAL_MULTI_SEND = 4003;
    const FAIL_INTERNAL_MULTI_RESPONSE = 4004;
    const FAIL_ACTION_NOT_REACHABLE  = 4005;
    const FAIL_REQUEST_METHOD        = 4006;
    const FAIL_PARAMETER_MISSING     = 4007;
    const FAIL_PARAMETER_TYPE        = 4008;
    const FAIL_OBJECT_NO_THIS_PROPERTY = 4009;
    const FAIL_USER_UID_OR_NAME_NOT_EXISTS = 4010;

    const FAIL_EMPTY_ACCOUNT = 5000;
    const FAIL_EMPTY_PASSWORD = 5001;
    const FAIL_WRONG_ACCOUNT_OR_PASSWORD = 5002;
    const FAIL_LOGIN_TOO_FREQUENTLY = 5003;
    const FAIL_USER_NAME_ALREADY_EXISTS = 5004;
    const FAIL_DATABASE_ERROR = 5005;
    const FAIL_USER_NOT_EXISTS = 5006;
    const FAIL_PASSWORD_LENGTH = 5007;
    const FAIL_INVALID_PASSWORD = 5008;
    const FAIL_INVALID_IP       = 5009;
    const FAIL_USER_CREATE_TOO_FREQUENTLY = 5010;
    const FAIL_USER_TOKEN_EXPIRE  = 5011;
    const FAIL_UPLOAD_EMPTY_FILE  = 5012;
    const FAIL_UPLOAD_FILE_TYPE   = 5013;
    const FAIL_UPLOAD_FILE_SIZE   = 5014;
    const FAIL_LOGIN_FAILED       = 5015;
}